### PR TITLE
Update unittests.yml -- add manual trigger

### PR DESCRIPTION
**Pull request by jGaboardi**
Update unittests.yml --  add manual trigger -- CI has been disabled for 3 months

### CODE REVIEW

**Comment by jGaboardi** [comment]
@knaaptime All green

**Comment by martinfleis** [comment]
> CI has been disabled for 3 months

any guess why?

**Comment by jGaboardi** [comment]
> > CI has been disabled for 3 months
> 
> any guess why?

Your guess is as good as mine. Perhaps disabled automatically at some point?

**Comment by martinfleis** [comment]
Ah, yeah. Probably due to commit inactivity after 6 months.

**Pull request merged**
