### PR TITLE
July release readthedocs tweaks

### PR DESCRIPTION
**Pull request by renanxcortes**
This updates the auxiliary files to generate the docs for readthedocs according to what was discussed in https://github.com/pysal/segregation/issues/58

I still didn't manage to run `make html` because I'm running into some issues with sphinx (specifically this one: https://github.com/rtfd/readthedocs.org/issues/4057). Could someone try to run with your sphinx to see if the files would be generated?

### CODE REVIEW

**Comment by renanxcortes** [comment]
So, this morning I manage to run `make html` with my notebook here in the center :) (I was having some issue with sphinx as I mentioned with the other one I was working on)

I hope all the files of readthedocs are ok, now, @sjsrey

**Comment by renanxcortes** [comment]
> @renanxcortes can you remove the `doc/_build` folder and everything inside it? readthedocs will rebuild this folder for us, so this is a duplicate.

Sure, thanks! Just removed now!

**Comment by weikang9009** [comment]
I ran into this error when trying to run `make html`:
image

**Comment by renanxcortes** [comment]
> I ran into this error when trying to run `make html`:
> image

Hm.. interesting... actually I'm running it smoothly:

image


image

**Comment by weikang9009** [comment]
Never mind. I forgot that I did not configure my Mac properly for testing `segregation`. It is working ok! (that is why I deleted the comment earlier)

**Comment by renanxcortes** [comment]
> id not configure my Mac properly for testing `segregation`. It is working ok! (that is why I deleted the comment

No problem! Could we merge? I'm curious if this is gonna work in the readthedocs, page :)

Thank you so much, Wei!

**Comment by weikang9009** [comment]
The api page looks great!

Several issues about the current docs:
* We do not need a duplicate of conf.py? https://github.com/pysal/segregation/blob/master/doc/_conf.py
* landing page title indentation https://github.com/pysal/segregation/blob/master/doc/index.rst
* "References" page is not configured (empty) even though it is showing in the menu?
image

**Comment by weikang9009** [comment]
I think this is going to work on readthedocs if we configure the readthedocs environment properly. It looks pretty good locally!

**Comment by renanxcortes** [comment]
> The api page looks great!
> 
> Several issues about the current docs:
> 
> * We do not need a duplicate of conf.py? https://github.com/pysal/segregation/blob/master/doc/_conf.py
> * landing page title indentation https://github.com/pysal/segregation/blob/master/doc/index.rst
> * "References" page is not configured (empty) even though it is showing in the menu?
>   image

ow, cool! Now I realized that I can open the index.html generated to test locally! Sure, I'll work in these issues! Thanks!

**Comment by knaaptime** [comment]
here's a higher-res version if you'd like
download

**Comment by renanxcortes** [comment]
@weikang9009 I think I fixed the readthedocs and improved a little bit the page. Could you take a look to see if this is okay?

**Pull request merged**
