### PR TITLE
make rvlib optional

### PR DESCRIPTION
**Pull request by knaaptime**

### CODE REVIEW

**Comment by knaaptime** [comment]
@jGaboardi  any idea why the tests arent firing for this PR?

**Comment by jGaboardi** [comment]
@knaaptime The workflow was simply disabled due to inactivity. I re-enabled just now. If you push another dummy commit that should trigger a workflow run.

Screenshot 2022-12-12 at 2 55 33 PM

**Comment by knaaptime** [comment]
you rule. thanks

assuming this passes, i'll start putting together a new release. Is there more of the latest and greatest scaffolding we should add before that?

**Comment by jGaboardi** [comment]
> assuming this passes, i'll start putting together a new release. Is there more of the latest and greatest scaffolding we should add before that?

I would at the very least we trim down the testing matrix to a "sparse" one where we run Ubuntu against all Python versions, but macOS and Windows only against the latest Python version being tested. Also, we should see if we can get Python 3.11 up in the fold.

**Pull request merged**
