### PR TITLE
testing

### PR DESCRIPTION
**Pull request by knaaptime**
use xdist

### CODE REVIEW

**Comment by knaaptime** [comment]
@jGaboardi the tests are correct now, but fail when xdist tries to read a file before it exists. We [solved this](https://github.com/oturns/geosnap/blob/88ae3c7ab76ddacdb35d7ab3691803591d455796/geosnap/tests/test_isochrones.py#L31) in geosnap using groups, but I don't remember how to assign groups... 🙃

**Comment by jGaboardi** [comment]
I think just like the link there for `geosnap`, no?

**Comment by jGaboardi** [comment]
I'll try to take a look later.

**Comment by knaaptime** [comment]
> I think just like the link there for geosnap, no?

well yes, but I cant remember which tests need to go in the same group to avoid the co-read

**Comment by knaaptime** [comment]
honestly i think the answer is to refactor the tests fairly substantially so that we only need to read the file in once

**Comment by jGaboardi** [comment]
We can also create `conftest.py` and run that [`get_data()`](https://github.com/oturns/geosnap/blob/88ae3c7ab76ddacdb35d7ab3691803591d455796/geosnap/tests/test_isochrones.py#L15) in a [`pytest_sessionstart()`](https://stackoverflow.com/a/40673918/8692996). That will run it once and only once before any tests start.

**Pull request merged**
