### PR TITLE
macOS testing -- Intel & Apple Silicon CI -- update testing.yml

### PR DESCRIPTION
**Pull request by jGaboardi**
* This PR adds explicit testing against Intel & Apple Silicon on macOS
* xref https://github.com/pysal/pysal/issues/1298

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]

**Comment by jGaboardi** [comment]
testing had been disabled....

**Comment by martinfleis** [comment]
I only checked the yaml, which is fine. Just merge this, it should kick the tests on again, no?

**Comment by jGaboardi** [comment]
@knaaptime Do you have nay idea about that Python 312 - Windows failure? We were previously testing Windows against Python 3.11 and I bumped it up in the PR.

**Comment by knaaptime** [comment]
no idea

**Pull request merged**
