### PR TITLE
update testing

### PR DESCRIPTION
**Pull request by knaaptime**
use latest pysal conventions

### CODE REVIEW

**Comment by jGaboardi** [comment]
Got it working with single core on CI. Now trying again with multi-core.

**Comment by jGaboardi** [comment]
Seems to be a [`quilt` cache error](https://github.com/pysal/segregation/actions/runs/8312243402/job/22746878476#step:4:184) when running CI via multicore.


```
==================================== ERRORS ====================================
________ ERROR collecting segregation/tests/test_multiscalar_profile.py ________
segregation/tests/test_multiscalar_profile.py:10: in <module>
    p = quilt3.Package.browse('osm/metro_networks_8k', "s3://spatial-ucr/")
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/telemetry.py:135: in decorated
    results = func(*args, **kwargs)
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/packages.py:584: in browse
    return cls._browse(name=name, registry=registry, top_hash=top_hash)
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/packages.py:611: in _browse
    tmp_path.rename(local_pkg_manifest)
../../../micromamba/envs/test/lib/python3.12/pathlib.py:1363: in rename
    os.rename(self, target)
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.cache/Quilt/v0/manifest/3f08088ceabbc6e8d5f8ad1699b254bab0c0ca3808e4893a43ec478ac1fb6ebf.tmp' -> '/home/runner/.cache/Quilt/v0/manifest/3f08088ceabbc6e8d5f8ad1699b254bab0c0ca3808e4893a43ec478ac1fb6ebf'
------------------------------- Captured stderr --------------------------------

Downloading manifest:   0%|          | 0.00/107k [00:00<?, ?B/s]
Downloading manifest: 100%|██████████| 107k/107k [00:00<00:00, 355kB/s]
Downloading manifest: 100%|██████████| 107k/107k [00:00<00:00, 354kB/s]
________ ERROR collecting segregation/tests/test_multiscalar_profile.py ________
segregation/tests/test_multiscalar_profile.py:10: in <module>
    p = quilt3.Package.browse('osm/metro_networks_8k', "s3://spatial-ucr/")
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/telemetry.py:135: in decorated
    results = func(*args, **kwargs)
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/packages.py:584: in browse
    return cls._browse(name=name, registry=registry, top_hash=top_hash)
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/packages.py:620: in _browse
    pkg = cls._from_path(local_pkg_manifest)
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/packages.py:628: in _from_path
    pkg = cls._load(open_file)
../../../micromamba/envs/test/lib/python3.12/site-packages/quilt3/packages.py:793: in _load
    meta = reader.read()
../../../micromamba/envs/test/lib/python3.12/site-packages/jsonlines/jsonlines.py:147: in read
    six.raise_from(EOFError, None)
<string>:3: in raise_from
    ???
E   EOFError
```

**Comment by jGaboardi** [comment]
xref #225

**Comment by knaaptime** [comment]
the way i skirted that multicore thing recently is to [group tests](https://github.com/oturns/geosnap/blob/7a81b6c36e8a483cfcb9d3131b295d66618494a0/geosnap/tests/test_isochrones.py#L31) that read from that file so they run on the same worker

**Comment by knaaptime** [comment]
does this supercede 225?

**Comment by jGaboardi** [comment]
Did not mean to edit your comment @knaaptime. I think my brain is still off...

**Comment by jGaboardi** [comment]
> does this supercede 225?

Yes.

> the way i skirted that multicore thing recently is to [group tests](https://github.com/oturns/geosnap/blob/7a81b6c36e8a483cfcb9d3131b295d66618494a0/geosnap/tests/test_isochrones.py#L31) that read from that file so they run on the same worker

Woah! Never seen this before. Let's try to implement here in a subsequent PR.

**Pull request merged**
