### PR TITLE
release prep

### PR DESCRIPTION
**Pull request by knaaptime**
still working a bit onthe readme, but checking this in as it resolves the last of the release checklist

### CODE REVIEW

**Comment by renanxcortes** [comment]
This is absolutely awesome so far! So, specifically for the ReadMe, I think we need to address two things:
- Put the Decomposition title before the paragraph that starts "Another useful analytics that can be performed..."
- Rename the second notebook in the readme from `using euclidian distances` to something more generic. Only a specific set of indexes use euclidian distances and, also, the nature of some indexes do not even use the concept of distance. So, one option for this link would be `using vector-based spatial data`.

Regarding notebooks, sphinx documentation and tests for the new names `SingleValueTest` and `TwoValueTest` I can do this after merging this PR, ok?

**Comment by knaaptime** [comment]
+1, there's another big commit coming on the readme

**Comment by renanxcortes** [comment]
Also, I was thinking here that we can also address that DOI badge in this PR :)

**Comment by knaaptime** [comment]
Unfortunately that will have to be the next one. The badge doesn't get created until the release. Will do a small PR after the bump that only updates  the readme

**Comment by renanxcortes** [comment]
> Unfortunately that will have to be the next one. The badge doesn't get created until the release. Will do a small PR after the bump that only updates the readme

Got it!

**Comment by renanxcortes** [comment]
Ok, cool, this ReadMe got really pleasing.

But I still think some 3 things need to be addressed:

- Actually, `using spatial weights matrices & euclidian distances` don't reflect the nature of these set of indexes. For example, The Boundary Spatial Dissimilarity uses the shared boundary of two sets of polygons, the perimeter area index uses the ratio of the perimeter and area, all concentration indexes (DEL, ACO, RCO) deals with the polygon area and sorting them according to the area. All of those indexes (and other we might add) do not use a spatial weight matrices.

- We could also use the income example call for SpatialDissim to be harmonized with the previous call:

`spatial_index = SpatialDissim(gdf, "hi_income", "total_population")`

- Actully, we do not require GeoDataFrame for the MultiGroup Measures so the sentence `though note, again, that now we requre a GeoDataFrame for proper estimation` can be dropped.

**Comment by knaaptime** [comment]
>Actually, using spatial weights matrices & euclidian distances don't reflect the nature of these set of indexes. For example, The Boundary Spatial Dissimilarity uses the shared boundary of two sets of polygons, the perimeter area index uses the ratio of the perimeter and area, all concentration indexes (DEL, ACO, RCO) deals with the polygon area and sorting them according to the area. All of those indexes (and other we might add) do not use a spatial weight matrices.

that shared boundary is calculated with... a spatial weights matrix :P

**Comment by renanxcortes** [comment]
> that shared boundary is calculated with... a spatial weights matrix :P

Hehehehe, you're right, I didn't pay attention to that! 
Everything ok with the last commit! I think this is good to go! Thank you!!

**Pull request merged**
