### PR TITLE
init dev container recipe

### PR DESCRIPTION
**Pull request by knaaptime**
add setup for codespaces
Screenshot 2022-12-27 at 10 42 09 PM

### CODE REVIEW

**Comment by jGaboardi** [comment]
Looks like the failures are due to the [`numpy` problem](https://github.com/pysal/libpysal/issues/500#issuecomment-1366273194). Looks good for merging. I'm interested in seeing how this works.

**Review by jGaboardi — APPROVED** [review]

**Comment by knaaptime** [comment]
@jGaboardi its neat. The files here setup the 'requirements` for a container that will clone your repo and open vscode inside. If you start a new codespace, it should open with everything you need to develop in the cloud, including running the notebooks

**Comment by jGaboardi** [comment]
Yeah, I just tried it and saw that. Very cool. But the current `numba`/`numpy` trouble damped the notebook experience...

**Comment by knaaptime** [comment]
if you wanna play around just use `pip install numpy==1.23` once the container boots

**Pull request merged**
