### PR TITLE
Versioneer

### PR DESCRIPTION
**Pull request by sjsrey**
We have a circular import that arises in the move to versioneer.

Issue crops up at  `segregation/aspatial/aspatial_indexes.py` when testing version for deprecation decorators (Line 21)

### CODE REVIEW

**Review by jGaboardi — COMMENTED** [review]
As far as the `versioneer` stuff, this looks good. I'm wondering how to solve that circular import problem though.

**Comment by sjsrey** [comment]
> As far as the `versioneer` stuff, this looks good. I'm wondering how to solve that circular import problem though.

https://github.com/sjsrey/segregation/commit/fa6a08ca41982bcd07081800a46ca83b1f649064

> As far as the `versioneer` stuff, this looks good. I'm wondering how to solve that circular import problem though.

https://github.com/sjsrey/segregation/commit/fa6a08ca41982bcd07081800a46ca83b1f649064

**Review by jGaboardi — APPROVED** [review]

**Comment by knaaptime** [comment]
we could just go ahead and remove the deprecated modules. Instead of allowing the functions to work with a deprecation warning, we could remove everything except for a warning explaining that if you need the old API, you need to downgrade `segregation<2`

**Comment by sjsrey** [comment]
> we could just go ahead and remove the deprecated modules. Instead of allowing the functions to work with a deprecation warning, we could remove everything except for a warning explaining that if you need the old API, you need to downgrade `segregation<2`

+1 as we said we would be removing the deprecation warnings in 2.2.0.

**Review by martinfleis — APPROVED** [review]

**Pull request merged**
