### PR TITLE
remove pygeos

### PR DESCRIPTION
**Pull request by martinfleis**
Not sure why pygeos is in requirements and CI ends here as it doesn't seem to be used in the code. Removing.

### CODE REVIEW

**Comment by martinfleis** [comment]
Huh? How come this PR caused a failure? Anyone closer to segregation code can tell me what is wrong?

**Comment by knaaptime** [comment]
weird. I'll dig into it 

thanks for putting this together

**Comment by jGaboardi** [comment]
Very strange indeed. Seems to be coming from [deep within `joblib`/`futures`](https://github.com/pysal/segregation/actions/runs/4645646848/jobs/8221757410#step:6:284)?

**Comment by jGaboardi** [comment]
How and why *removing* the `pygeos` dependency would lead to that path is a bit of mystery...

**Comment by martinfleis** [comment]
It is not caused by this PR. See main https://github.com/pysal/segregation/actions/runs/4642225334/jobs/8215907349. For some reason, the workflow is marked as successful even when it failed in all envs :D.

**Comment by martinfleis** [comment]
https://github.com/pysal/segregation/blob/b3643f7af0aeaed1caf5a39b4e57c19a5c5f3459/.github/workflows/unittests.yml#L16

**Comment by knaaptime** [comment]
i thought the continue on error was supposed to just keep running tests on all platforms even when one fails (to make sure its not isolated to windows or something) but maybe im wrong

the good news is it looks like the issue is limited to that single inference test (based on individual-level permutation) so i'll take a closer look at that function today

**Comment by knaaptime** [comment]
(im fine to go ahead and merge this PR then and work on the failure separately)

**Comment by jGaboardi** [comment]
Looks like this started failing [5 days ago](https://github.com/pysal/segregation/actions/runs/4602442267).

**Review by jGaboardi — APPROVED** [review]

**Comment by martinfleis** [comment]
> i thought the continue on error was supposed to just keep running tests on all platforms even when one fails

That is `fail-fast`.

**Pull request merged**
