### PR TITLE
start counterfactual

### PR DESCRIPTION
**Pull request by knaaptime**
this PR starts a function to generate counterfactual variables for two cities using the "unit share" approach. Still need to add the other two approaches

### CODE REVIEW

**Comment by renanxcortes** [comment]
This is a pretty good start! I just think that would be more 'integrated' with the module, if the user passes a segregation class to this function and internally the function will use the 'group_pop_var' and 'total_pop_var' variable through the .core_data attribute that all segregation class have... so the df1 and df2 would be something similar like this (illustrated by data_1 and data_2):

image

**Comment by renanxcortes** [comment]
Or perhaps your way is even more generic since in my suggestion is restricted to only two groups... In any case, I'm merging it to have this start and then work on these details later.

**Comment by knaaptime** [comment]
yeah that's a good point. My thought was that we might want the counterfactul variables available as dataframes (e.g. for plotting), but could think about accepting segregation classes instead.

i guess the other benefit of doing it this way is that hopefully we won't need to rewrite as we make progress on #4

**Comment by knaaptime** [comment]
using this approach, we can keep the `decompose` function, only now it would take two segregation classes, call `generate_counterfactual` internally, and return the shapley components

**Comment by renanxcortes** [comment]
Yes, this is exactly what I thought! We can build a nested framework for the decomposition.

**Pull request merged**
